# Generated by Django 3.2.6 on 2021-08-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=256)),
                ('provider', models.CharField(max_length=256)),
                ('provider_id', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('wallet_expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_expenses', to='wallets.wallet')),
                ('wallet_income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_income', to='wallets.wallet')),
            ],
        ),
    ]
