# Generated by Django 3.2.6 on 2021-08-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallet_name'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wallet_expenses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_expenses', to='wallets.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_income', to='wallets.wallet'),
        ),
    ]
