# Generated by Django 3.2.6 on 2021-09-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_supplier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='provider_id',
        ),
    ]
