# Generated by Django 3.2.6 on 2021-08-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210825_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('in', 'Income'), ('ex', 'Expenses'), ('tr', 'Transfer')], default='in', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='amount_expensys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='amount_income',
            field=models.IntegerField(default=0),
        ),
    ]
