# Generated by Django 3.2.6 on 2021-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_amount_expensys_item_amount_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
