# Generated by Django 3.2.6 on 2021-08-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210827_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
