# Generated by Django 3.2.6 on 2021-09-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210827_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#9E9E9E', max_length=16),
        ),
    ]
