# Generated by Django 3.2.6 on 2021-08-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('color', models.CharField(default='#9E9E9E', max_length=8)),
                ('amount', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=16)),
                ('kind', models.CharField(max_length=32)),
                ('is_favarite', models.BooleanField(default=False)),
                ('is_hide', models.BooleanField(default=False)),
            ],
        ),
    ]
