# Generated by Django 3.2.6 on 2021-08-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_rename_is_favarite_wallet_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
