# Generated by Django 3.2.6 on 2021-08-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='code',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
