# Generated by Django 3.2.6 on 2021-09-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_wallet_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='color',
            field=models.CharField(default='#9E9E9E', max_length=16),
        ),
    ]
