version: '3'

services:
  kaizu-app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    network_mode: service:kaizu-db
  kaizu-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - kaizu-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  kaizu-postgres-data: